version: '3'

services:
  postgresql:
    container_name: postgresql
    image: postgres:14
    restart: on-failure
    network_mode: bridge
    environment:
      - POSTGRES_USER=waas 
      - POSTGRES_PASSWORD=WaasPassw0rd
      - POSTGRES_DB=waas
      - DATABASE_HOST=0.0.0.0
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  
  waas:
    # to build the docker image from the source
    build:
      dockerfile: Dockerfile
      context: .
      target: waas
    # image: waas:latest
    container_name: waas
    network_mode: bridge
    cap_add:
      - NET_ADMIN
    volumes:
      - "waas-data:/data"
    #   - "./config.yaml:/config.yaml" # if you have a custom config file
    ports:
      - "8000:8000/tcp"
      - "51820:51820/udp"
    devices:
      - "/dev/net/tun:/dev/net/tun"
    depends_on:
      - postgresql
      - redis
  
  redis:
    image: redis:6.2.5
    container_name: redis
    restart: on-failure
    network_mode: bridge
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379

  worker:
    # to build the docker image from the source
    build:
      dockerfile: Dockerfile
      context: .
      target: worker
    # image: waas:latest
    container_name: waas-worker
    network_mode: bridge
    cap_add:
      - NET_ADMIN
    volumes:
      - "waas-data:/data"
    #   - "./config.yaml:/config.yaml" # if you have a custom config file
    devices:
      - "/dev/net/tun:/dev/net/tun"
    depends_on:
      - waas
      - postgresql
      - redis

volumes:
  data:
    driver: local
  waas-data:
    driver: local