version: '3'

services:
  postgresql:
    container_name: postgresql
    image: postgres:14
    restart: on-failure
    environment:
      - POSTGRES_USER=waas 
      - POSTGRES_PASSWORD=WaasPassw0rd
      - POSTGRES_DB=waas
      - DATABASE_HOST=0.0.0.0
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      bridgenet:
        aliases:
          - postgresql
  
  waas:
    # to build the docker image from the source
    # build:
    #   dockerfile: Dockerfile
    #   context: .
    #   target: waas
    image: ghcr.io/waas-app/waas-waas:latest
    container_name: waas
    cap_add:
      - NET_ADMIN
    volumes:
      - "waas-data:/data"
      - ./waas/yml:/waas.yml
    #   - "./config.yaml:/config.yaml" # if you have a custom config file
    ports:
      - "8000:8000/tcp"
      - "51810:51810/udp"
    devices:
      - "/dev/net/tun:/dev/net/tun"
    depends_on:
      - postgresql
      - redis
    networks:
      bridgenet:
        aliases:
          - waas
  
  redis:
    image: redis:6.2.5
    container_name: redis
    restart: on-failure
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379
    networks:
      bridgenet:
        aliases:
          - redis

  worker:
    # to build the docker image from the source
    # build:
    #   dockerfile: Dockerfile
    #   context: .
    #   target: worker
    image: ghcr.io/waas-app/waas-worker:latest
    container_name: worker
    cap_add:
      - NET_ADMIN
    volumes:
      - "waas-data:/data"
      - ./waas/yml:/waas.yml
    #   - "./config.yaml:/config.yaml" # if you have a custom config file
    devices:
      - "/dev/net/tun:/dev/net/tun"
    depends_on:
      - waas
      - postgresql
      - redis
    networks:
      bridgenet:
        aliases:
          - worker

volumes:
  data:
    driver: local
  waas-data:
    driver: local

networks:
  bridgenet:
    name: "bridge-network"
    driver: "bridge"